# Generated by Django 3.1.7 on 2021-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect', models.CharField(max_length=32)),
                ('bat', models.FloatField()),
                ('fix', models.IntegerField()),
                ('num_sat', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt', models.FloatField()),
                ('zspeed', models.FloatField()),
                ('gspeed', models.FloatField()),
                ('heading', models.IntegerField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('arm', models.BooleanField()),
                ('armable', models.BooleanField()),
                ('ekf', models.BooleanField()),
                ('mode', models.CharField(max_length=32)),
                ('mission', models.CharField(max_length=32)),
            ],
        ),
    ]
