# Generated by Django 3.1.7 on 2021-08-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210805_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='user',
        ),
    ]
