# Generated by Django 3.1.7 on 2021-04-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210408_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='command',
            new_name='Command',
        ),
    ]
