# Generated by Django 3.1.7 on 2021-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210408_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('coordinates', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
