# Generated by Django 3.1.7 on 2021-06-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210616_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dronecommand',
            old_name='Command',
            new_name='command',
        ),
    ]
